spring:
  application:
    name: HystrixDashBoard
  jackson:
    serialization:
      indent-output: true    
server:
  port: 8695
eureka:
  client:
    service-url:
      defaultzone: http://localhost:8761/eureka
      
management:
  endpoint:
    health:
      show-details: always      
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  hystrix:
    enabled: true

  
